name: "WireGuard Connect"
description: "Bring up a WireGuard tunnel on Ubuntu runners with dynamic domain-based routing."
author: "Rohit TP"
branding:
  icon: "shield"
  color: "blue"

inputs:
  config:
    description: "Base64-encoded wg-quick config (wg0.conf)"
    required: true
  iface:
    description: "WireGuard interface name"
    required: false
    default: "wg0"
  domains:
    description: "Comma-separated list of domains to route through WireGuard (for split tunneling). If not specified, all traffic is routed through WireGuard."
    required: false
    default: ""
  ips:
    description: "Comma-separated list of IP addresses (IPv4 or IPv6) to route through WireGuard."
    required: false
    default: ""

outputs:
  public_ip:
    description: "Public IP visible after tunnel is up (if check_ip=true)"

runs:
  using: "node24"
  main: "dist/index.js"
